{% set python_min = '3.10' %}
{% set name = "pyospackage" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyospackage-{{ version }}.tar.gz
  sha256: dd46b78c1ccd8a5affcf8b6e64000e9cd101c40be6562d48a39aa3f10d83d684

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyospackage
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pyospackage/
  summary: A package that adds numbers together
  doc_url: https://pyospackage.readthedocs.io/en/latest/
  dev_url: https://github.com/pyopensci/pyospackage
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lwasser
