{% set name = "pyospackage" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyospackage-{{ version }}.tar.gz
  sha256: 7b463f7b385613d4e63ce2efb47fd380f2f2fb8c3efb23d503beece5e507a946

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.10

test:
  imports:
    - pyospackage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pyospackage/
  summary: A package that adds numbers together
  doc_url: https://pyospackage.readthedocs.io/en/latest/
  dev_url: https://github.com/pyopensci/pyospackage
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lwasser
